// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter/material.dart'; // Required for TargetPlatform

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkND8DLf7tOOgfzAoq46RH83wiiOePoIw',
    appId: '1:81269719003:web:fa11df02d4470d882bb1fe',
    messagingSenderId: '81269719003',
    projectId: 'eventlyapp-3a4ad',
    authDomain: 'eventlyapp-3a4ad.firebaseapp.com',
    storageBucket: 'eventlyapp-3a4ad.firebasestorage.app',
    measurementId: 'G-VF9DVX6ZT4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB97kU70Yb2yXoje_RF9uyGnhuYLoaePps',
    appId: '1:81269719003:android:9635fcaf7c2ad5962bb1fe',
    messagingSenderId: '81269719003',
    projectId: 'eventlyapp-3a4ad',
    storageBucket: 'eventlyapp-3a4ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1gWI4ka42D8Y8hL3HRXmyejPqGAJLeoI',
    appId: '1:81269719003:ios:76086f54372968262bb1fe',
    messagingSenderId: '81269719003',
    projectId: 'eventlyapp-3a4ad',
    storageBucket: 'eventlyapp-3a4ad.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1gWI4ka42D8Y8hL3HRXmyejPqGAJLeoI',
    appId: '1:81269719003:ios:76086f54372968262bb1fe',
    messagingSenderId: '81269719003',
    projectId: 'eventlyapp-3a4ad',
    storageBucket: 'eventlyapp-3a4ad.appspot.com',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkND8DLf7tOOgfzAoq46RH83wiiOePoIw',
    appId: '1:81269719003:web:d37e051099749a322bb1fe',
    messagingSenderId: '81269719003',
    projectId: 'eventlyapp-3a4ad',
    authDomain: 'eventlyapp-3a4ad.firebaseapp.com',
    storageBucket: 'eventlyapp-3a4ad.appspot.com',
    measurementId: 'G-NJCEFQK1WC',
  );
}